import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {clsx} from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OUTFIT",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "https://drive.google.com/file/d/1Wl-p9q5c2F6TNqGzqlFWd23sGTiRiicT/view?usp=sharing",
      },
    ],
  },
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx(inter.className, "antialiased")}>
      {children}
      </body>
    </html>
  );
}
