import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {clsx} from "clsx";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "OUTFIT",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "https://outfit-ur-stylist.vercel.app/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Foutfit_gif.9d6f379b.gif&w=3840&q=75",
      },
    ],
  },
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={clsx(inter.className, "antialiased")}>
      {children}
      </body>
    </html>
  );
}
