import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {clsx} from "clsx";
import localFont from "next/font/local";

const inter = Inter({ subsets: ["latin"] });

// Add your custom font
const outfitFont = localFont({
  src: "../../public/fonts/Outfit-SemiBold.ttf",
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "OUTFIT",
  description: "Generated by create next app",
  openGraph: {
    images: [
      {
        url: "https://drive.google.com/file/d/1Wl-p9q5c2F6TNqGzqlFWd23sGTiRiicT/view?usp=sharing",
      },
    ],
  },
};

export default function RootLayout({children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en" className={outfitFont.variable} suppressHydrationWarning>
      <body className={clsx(inter.className, "antialiased")}>
      {children}
      </body>
    </html>
  );
}
